name = "central-marketing"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[vars]
VITE_SUPABASE_URL = "https://dydivsegegbxqwfdubbd.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZGl2c2VnZWdieHF3ZmR1YmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA3MTAxNzMsImV4cCI6MjEwNjI4NjE3M30.pG-9dIOkjfW7dLPpE5wGtQACZHsFj6MRRkX2zI5trjw"
VITE_GEMINI_API_KEY = "AQ.Ab8RN6IojjS93rcJrlbe99KWi90uUXOoLC4k_nEBiRdlgQSIww"
VITE_GROQ_API_KEY = "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"
